### PR TITLE
Style: Rubocop auto-correct

### PR DESCRIPTION
**Pull request by jekyllbot**
PR automatically created for @DirtyF.

```text
Style: Rubocop auto-correct
```

### CODE REVIEW

**Comment by pathawks** [comment]
Seems like it’s testing with Jekyll `3.6.0` instead of `3.6.2` 🤔

**Comment by DirtyF** [comment]
@pathawks bundler cache? Should we force bundle update?

**Comment by localheinz** [comment]
@benbalter 

Build is failing, but currently builds based on `master` are failing because of rubocop complaining - any chances on either fixing this PR here or approving #247 instead?

**Comment by DirtyF** [comment]
@jekyllbot: merge +dev

**Comment by DirtyF** [comment]
@localheinz done.

**Pull request merged**
