### PR TITLE
Added site.logo as an alternate OG image (if page.image doesn’t exist)

### PR DESCRIPTION
**Pull request by aarongustafson**

### CODE REVIEW

**Comment by aarongustafson** [comment]
Just saw the tests… fixing now.

**Comment by aarongustafson** [comment]
Looks like Rubocop is barking at master (stuff I didn’t touch). Do you want me to fix the issues?

**Comment by aarongustafson** [comment]
Fixes #168

**Comment by DirtyF** [comment]
@aarongustafson nice contribution ❤️ 

`rubocop -a` should fix some offenses but if this is not related to your PR this can be fixed later in a dedicated PR

**Comment by pathawks** [comment]
> this is not related to your PR this can be fix later in a dedicated PR

:+1:

**Comment by DirtyF** [comment]
@pathawks done in #170

**Comment by aarongustafson** [comment]
@DirtyF Thanks!

**Comment by benbalter** [comment]
See https://github.com/jekyll/jekyll-seo-tag/issues/168#issuecomment-290896438:

> The reason we want the user to explicitly define an image instead of just falling back to the logo or something is because there may be instances where a user would rather include no image than include the logo. If this is not the case, the user can easily specify a site-wide default image to use.
 
Thoughts?

**Comment by aarongustafson** [comment]
@benbalter Somehow I missed that in the docs. The PR is unnecessary.

**Pull request closed without merging**
