### PR TITLE
Update Page description to include page number

### PR DESCRIPTION
**Pull request by alokpant**
Issue: https://github.com/jekyll/jekyll-seo-tag/issues/265
Add page number to description if it is not first page.
First Page Description: 'My Description'
Other pages: 'My Description - Page 1 of 2'

### CODE REVIEW

**Comment by alokpant** [comment]
@benbalter Earlier version of code works. Is there a way to test code I have written works as well? 

Should I also try to include spec for new code that I have added? I tried to write it but wasn't successful. I looked into helper method to see if I can reuse any, there are methods on creating single pages but none for multiple ones. If specs are needed, I would probably need direction or help around how to how to create multiple pages.

**Comment by DirtyF** [comment]
@alokpant 

I think you should be able to pass options to the `make site` method. here you would need to pass pagination options, build the site, then check that the descriptions of the paginated pages are OK.

**Comment by alokpant** [comment]
@DirtyF I tried it last week, couldn't manage to do it. I will try it this week.

**Comment by alokpant** [comment]
@DirtyF I tried to pass paginator option as part of config, but @context['paginator'] was still nil.
```
        let(:config) {
          {
            :description => "My site description",
            :paginator => {
              page: 2,
              total_pages: 3
            }
          }
        }
```

Can you please suggest what am I missing?

**Pull request closed without merging**
