### PR TITLE
Add `og:image:alt` and `twitter:image:alt`

### PR DESCRIPTION
**Pull request by tordans**
Twitter documentation https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image
> twitter:image:alt
A text description of the image conveying the essential nature of an image to users who are visually impaired. Maximum 420 characters.

Facebook / OG cocumentation
> og:image:alt - A description of what is in the image (not a caption). If the page specifies an og:image it should specify og:image:alt.

Closes https://github.com/jekyll/jekyll-seo-tag/issues/395

### CODE REVIEW

**Review by nickmccurdy — APPROVED** [review]
This looks great, thanks. Are you aware if it's possible to Jekyll to warn when `image` is used without `alt` though?

**Comment by tordans** [comment]
> This looks great, thanks. Are you aware if it's possible to Jekyll to warn when `image` is used without `alt` though?

No I would not know how Jekyll could do that; and don't think it's the intended behavior of this plugin - it does not warn anywhere else…

**Comment by mattr-** [comment]
Waiting for CI to come back green and will merge then.

**Comment by mattr-** [comment]
@jekyllbot: merge +minor

**Pull request merged**
