### PR TITLE
feat(image): Add meta twitter image

### PR DESCRIPTION
**Pull request by CaptainJojo**
# Description

In documentation for twitter card we need to add meta `twitter:image`
See: [https://dev.twitter.com/cards/types/summary](https://dev.twitter.com/cards/types/summary)

# Validate

See new meta `twitter:image` in page when image.path is config

### CODE REVIEW

**Comment by benbalter** [comment]
I believe this is not necessary. See https://dev.twitter.com/cards/getting-started#opengraph:

> When the Twitter card processor looks for tags on a page, it first checks for the Twitter-specific property, and if not present, falls back to the supported Open Graph property. This allows for both to be defined on the page independently, and minimizes the amount of duplicate markup required to describe content and experience.

**Comment by CaptainJojo** [comment]
Yes, it's not necessary but by default twitter take the first image in page but I need to specify my image :(

**Comment by benbalter** [comment]
> but I need to specify my image

If you specify it in the front matter, the plugin should output `og:image` which Twitter should use. Is that not the case?

**Comment by benbalter** [comment]
> but I need to specify my image

If you specify it in the front matter, the plugin should output `og:image` which Twitter should use. Is that not the case?

**Comment by CaptainJojo** [comment]
It's ok, I test directly in twitter og:image is take in twitter :)

**Pull request closed without merging**
