### PR TITLE
Use `smartify` instead of `markdownify`

### PR DESCRIPTION
**Pull request by jekyllbot**
PR automatically created for @pathawks.

```text
Use `smartify` instead of `markdownify`
```

### CODE REVIEW

**Comment by pathawks** [comment]
As pointed out by @ashmaroli, it looks like we reverted to using `markdownify` instead of `smartify`. (This happened in #184)

We switched to `smartify` in #19 because we are only using this for smart punctuation, and we do not need any HTML elements created (they will be stripped anyway).

**Comment by pathawks** [comment]
The one place I can think of where we might want to use `markdownify` is with `page.description`, which might be raw Markdown, and we would want to strip things like Markdown links.

**Comment by ashmaroli** [comment]
I find it odd that the variables have to go through the process of
`markdownify || smartify > strip_html > normalize_whitespace > escape_once` just to have regular strings converted to another regular string..
Of course, its a different thing with having to process `:description` since it could be `page.excerpt`

**Comment by benbalter** [comment]
What's the practical advantage to using Smartify over Markdownify? Potential performance? If `description` *might* be Markdown, and Markdown conversion is idempotent, I'd think we'd want to err on the side of better compatibility, no?

**Comment by pathawks** [comment]
There are times when I have used symbols in a title that could be confused with Markdown but are not intended as Markdown. I once had a title similar to `#Hashtag` which Markdown converted to `<h1>Hashtag</h1>` which was not what I had intended. (I don't think kramdown suffers from this problem; I think I was using RedCarpet at the time.)

I agree that this is not a big problem, and agree that for `description` we want to err on the side of compatibility.

**Pull request closed without merging**
