### PR TITLE
Test against Ruby 2.5

### PR DESCRIPTION
**Pull request by jekyllbot**
PR automatically created for @DirtyF.

```text
Test against Ruby 2.5
```

### CODE REVIEW

**Comment by pathawks** [comment]
Rubocop is complaining

**Comment by DirtyF** [comment]
@pathawks looks like jekyll 3.6.2 rubocop's config is the culprit here

**Comment by ashmaroli** [comment]
The solution here is to lock Rubocop to the version supported by Jekyll..
There's bound to be conflicts when we `inherit .rubocop.yml` from `jekyll` gem (uses Rubocop 0.51.0 max) yet the plugin uses a future version of Rubocop for development (Rubocop 0.52.1)

**Comment by DirtyF** [comment]
@jekyllbot: merge +dev

**Pull request merged**
