### PR TITLE
Google plus direct connect

### LINKED ISSUE #168: Fix `og:image` to fall back to the site image if one exists
The `meta` element doesn’t show up at all if `page.image` doesn’t exist.

### PR DESCRIPTION
**Pull request by aarongustafson**
Fixes #168

### CODE REVIEW

**Comment by pathawks** [comment]
I'm confused. I thought Google stopped supporting this years ago.

Is this something new/different?

https://support.google.com/webmasters/answer/6083347?hl=en
http://searchengineland.com/goodbye-google-authorship-201975

**Comment by pathawks** [comment]
[Google kills Google+ Direct Connect feature](https://searchenginewatch.com/sew/news/2351386/google-kills-google-direct-connect-feature) from 2014

**Comment by aarongustafson** [comment]
Doh! I still had it on my site. I guess it’s no longer needed.

Weird the docs still exist.

**Comment by aarongustafson** [comment]
Mwah mwah. Update your docs Google!

**Comment by pathawks** [comment]
@aarongustafson Thank you though. I think these discussions make the plugin better, even when a feature isn't ultimately added. I appreciate that we're all working together on this :beers:

**Pull request closed without merging**
